services:
  portainer-ce:
    image: portainer/portainer-ce:lts
    ports:
      - 8000:8000
      - 9443:9443
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - main-net
