services:
  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - main-net
