---
services:
  ispyagentdvr:
    image: mekayelanik/ispyagentdvr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - AGENTDVR_WEBUI_PORT=8090
      - TZ=Pacific/Auckland
    volumes:
      - ${ISPY_ROOT_DIR}/XML:/AgentDVR/Media/XML
      - ${ISPY_ROOT_DIR}/Media:/AgentDVR/Media/WebServerRoot/Media
      - ${ISPY_ROOT_DIR}/Commands:/AgentDVR/Commands
    ports:
      - 8090:8090
      - 3478:3478/udp
      - 50000-50100:50000-50100/udp
    restart: unless-stopped
    networks:
      - main-net
