services:
  filearchiver:
    image: ghcr.io/haepapa/filearchiver:prod
    container_name: filearchiver
    volumes:
      # backup paths
      - /mnt/work/share/archive:/data/input
      - /mnt/data/share/Archive:/data/output
      # persistent app data
      - filearchiver-data:/config
    # run first
    # command: ["-setup", "/config"]
    # then run
    # command: ["-init", "-config", "/config/config.yaml", "-ignorefile", "/config/.archiveignore"]
    # run ongoing
    command: ["-config", "/config/config.yaml", "-ignorefile", "/config/.archiveignore"]
    restart: "no"
    networks:
      - main-net
